export const AUTH_USER = 'AUTH_USER',
    AUTH_ERROR = 'AUTH_ERROR',
    FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST',
    RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'

export const GET_CLIENTS = "GET_CLIENTS", 
    GET_CLIENTS_ERROR ="GET_CLIENTS_ERROR"

export const CREATE_EXCEL_FILE = "CREATE_EXCEL_FILE"
